Add controllers
IgorMartynkin1981/java-shareit pull request #1
Opened 2022-09-07 12:53 UTC by IgorMartynkin1981

Refactor согласно ТЗ_13

2022-09-08 13:42 UTC, kukolev requested changes

2022-09-08 13:42 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/Item.java
> + * TODO Sprint add-controllers.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-09-08 13:42 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * TODO Sprint add-controllers.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-09-08 13:42 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemDto.java
> + * TODO Sprint add-controllers.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-09-08 13:42 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/MemoryItemDAOImpl.java
> +            throw new StorageException(String.format("There are no any items with ID %d!", itemId), HttpStatus.NOT_FOUND);
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-08 13:42 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/MemoryItemDAOImpl.java
> +            throw new StorageException(String.format("There are no any items with ID %d!", itemId), HttpStatus.NOT_FOUND);
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-08 13:42 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/User.java
>   * TODO Sprint add-controllers.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-09-08 13:42 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserController.java
>   * TODO Sprint add-controllers.
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-09-08 13:42 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        if (errors.hasErrors()) throw new ValidationException(errors, HttpStatus.BAD_REQUEST);
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-09-08 13:42 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            throw new ValidationException(String.format("User with email %s already exists!", user.getEmail()), HttpStatus.CONFLICT);
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-08 13:42 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +                throw new ValidationException(String.format("User with email %s already exists!", user.getEmail()), HttpStatus.CONFLICT);
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-09 12:10 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/Item.java
> + * TODO Sprint add-controllers.
Заметки убрал

2022-09-09 12:10 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * TODO Sprint add-controllers.
Заметки убрал

2022-09-09 12:11 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/ItemDto.java
> + * TODO Sprint add-controllers.
Заметки убрал

2022-09-09 12:11 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/user/User.java
>   * TODO Sprint add-controllers.
Заметки убрал

2022-09-09 12:11 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/user/UserController.java
>   * TODO Sprint add-controllers.
Заметки убрал

2022-09-09 12:17 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/MemoryItemDAOImpl.java
> +            throw new StorageException(String.format("There are no any items with ID %d!", itemId), HttpStatus.NOT_FOUND);
Выполнил перенос строки

2022-09-09 12:17 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/MemoryItemDAOImpl.java
> +            throw new StorageException(String.format("There are no any items with ID %d!", itemId), HttpStatus.NOT_FOUND);
Выполнил перенос строки

2022-09-09 12:33 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            throw new ValidationException(String.format("User with email %s already exists!", user.getEmail()), HttpStatus.CONFLICT);
Выполнил перенос строки

2022-09-09 12:33 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +                throw new ValidationException(String.format("User with email %s already exists!", user.getEmail()), HttpStatus.CONFLICT);
Выполнил перенос строки

2022-09-09 14:42 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        if (errors.hasErrors()) throw new ValidationException(errors, HttpStatus.BAD_REQUEST);
Логика перенесена в сервис

2022-09-09 15:06 UTC, kukolev requested changes

2022-09-09 15:06 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private boolean emailIsValid(String email) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-09-09 15:06 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private boolean itemIsValid(ItemDto item) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-09-09 15:13 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private boolean itemIsValid(ItemDto item) {
Изменил название метода на "checkItemForValid"

2022-09-09 15:14 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private boolean emailIsValid(String email) {
Изменил имя метода на "checkUserForValid"

2022-09-10 10:25 UTC, kukolev approved these changes

2022-09-10 14:11 UTC, merged