Add bookings
IgorMartynkin1981/java-shareit pull request #2
Opened 2022-09-28 13:11 UTC by IgorMartynkin1981

Refactor the code to the requirements of the specification №14

2022-09-28 13:30 UTC, IgorMartynkin1981 commented
Пришлось вернуть изначальные настройки application.properties

2022-09-29 08:16 UTC, kukolev requested changes

2022-09-29 08:16 UTC, kukolev commented on pom.xml
> +		<dependency>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-29 08:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/ShareItApp.java
>  	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-29 08:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +        if (booking.getState().equals(State.APPROVED)) {
Валидации лучше вынести в отдельный приватный метод. Тогда каждый метод будет отвечать за свою часть функционала и код будет проще анализировать. Код при этом может выглядеть примерно так:

```
public SomeResult someMethod(...) {
    validateSomething(...);
    // business-logic here
}

private void validateSomething(...) {
    if (/* ! check something /*) {
        throw new SomeException();
    }
}
```
Таким образом в методе someMethod визуально будет проще найти бизнес-логику, ради которой этот метод и создавался.

2022-09-29 08:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private void bookingValidation(BookingDto bookingDto, Long bookerId) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-09-29 08:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private void userValidation(Long userId) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-09-29 08:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    Long id;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-29 08:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/controllers/ItemController.java
> +        itemDto.setId(itemId);
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

2022-09-29 08:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/controllers/ItemController.java
> +        if (text.equals("")) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

2022-09-29 08:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dto/InfoItemDto.java
> +    Long id;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-29 08:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +    private Item itemValidation(Long itemId) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-09-29 08:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +    private void userValidation(Long userId) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-09-29 08:16 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-29 11:27 UTC, IgorMartynkin1981 commented on pom.xml
> +		<dependency>
Отступы приведены в соответствие с кодстайлом

2022-09-29 11:27 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/ShareItApp.java
>  	public static void main(String[] args) {
Отступы приведены в соответствие с кодстайлом

2022-09-29 12:00 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +        if (booking.getState().equals(State.APPROVED)) {
Все валидации вынес в отдельные методы

2022-09-29 12:01 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private void bookingValidation(BookingDto bookingDto, Long bookerId) {
Название метода привел в соответствие с кодстайлом

2022-09-29 12:01 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private void userValidation(Long userId) {
Название метода привел в соответствие с кодстайлом

2022-09-29 12:15 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/controllers/ItemController.java
> +        itemDto.setId(itemId);
Логика перенесена в Сервис

2022-09-29 12:16 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/controllers/ItemController.java
> +        if (text.equals("")) {
Логика перенесена в сервис

2022-09-29 13:34 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/dto/InfoItemDto.java
> +    Long id;
Поля сделал приватными

2022-09-29 13:35 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +    private Item itemValidation(Long itemId) {
Название метода привел в соответствие с кодстайлом

2022-09-29 13:35 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +    private void userValidation(Long userId) {
Название метода привел в соответствие с кодстайлом

2022-09-29 13:36 UTC, IgorMartynkin1981 commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
Раскомментировал код, всёс изменения для совместной работы

2022-09-29 13:37 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    Long id;
Поля сделал приватными

2022-09-30 08:50 UTC, kukolev requested changes

2022-09-30 08:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationOwnerIter(Long ownerId, Booking booking) {
Метод валидации назван некорректно. Слово «validation» это не глагол. Нужно переименовать.

2022-09-30 08:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationApprovedBooking(Booking booking) {
Метод валидации назван некорректно. Слово «validation» это не глагол. Нужно переименовать.

2022-09-30 08:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationRequestOnQwnerItemOrUserCreated(Long userId, Booking booking) {
Метод валидации назван некорректно. Слово «validation» это не глагол. Нужно переименовать.

2022-09-30 08:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationArgumentState(String state) {
Метод валидации назван некорректно. Слово «validation» это не глагол. Нужно переименовать.

2022-09-30 08:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private void validationBooking(BookingDto bookingDto, Long bookerId) {
Метод валидации назван некорректно. Слово «validation» это не глагол. Нужно переименовать.

2022-09-30 08:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationOwnerItem(Long bookerId, Item item) {
Метод валидации назван некорректно. Слово «validation» это не глагол. Нужно переименовать.

2022-09-30 08:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationAvailableItem(Item item) {
Метод валидации назван некорректно. Слово «validation» это не глагол. Нужно переименовать.

2022-09-30 08:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationCorrectBookingDates(BookingDto bookingDto, LocalDateTime timeNow) {
Метод валидации назван некорректно. Слово «validation» это не глагол. Нужно переименовать.

2022-09-30 08:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private void validationUser(Long userId) {
Метод валидации назван некорректно. Слово «validation» это не глагол. Нужно переименовать.

2022-09-30 08:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +        if (text.equals("")) {
Лучше сделать проверку так: `if (!"".equals(text))`. Тогда не будет выброшен NullPointerException, если text == null

2022-09-30 11:30 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private void validationUser(Long userId) {
Изменил имя метода

2022-09-30 11:30 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationOwnerIter(Long ownerId, Booking booking) {
Изменил имя метода

2022-09-30 11:31 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationApprovedBooking(Booking booking) {
Изменил имя метода

2022-09-30 11:31 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationRequestOnQwnerItemOrUserCreated(Long userId, Booking booking) {
Изменил имя метода

2022-09-30 11:31 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationArgumentState(String state) {
Изменил имя метода

2022-09-30 11:31 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private void validationBooking(BookingDto bookingDto, Long bookerId) {
Изменил имя метода

2022-09-30 11:31 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationOwnerItem(Long bookerId, Item item) {
Изменил имя метода

2022-09-30 11:31 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationAvailableItem(Item item) {
Изменил имя метода

2022-09-30 11:31 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +    private static void validationCorrectBookingDates(BookingDto bookingDto, LocalDateTime timeNow) {
Изменил имя метода

2022-09-30 11:34 UTC, IgorMartynkin1981 commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +        if (text.equals("")) {
Заменил условия if. Спасибо!

2022-10-01 08:05 UTC, kukolev approved these changes

2022-10-01 12:26 UTC, merged