Add item requests
IgorMartynkin1981/java-shareit pull request #3
Opened 2022-10-07 12:56 UTC by IgorMartynkin1981

Refactor the code to the requirements of specification #15

2022-10-08 11:31 UTC, kukolev requested changes

2022-10-08 11:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/bookingTests/BookingControllerTest.java
> +    ObjectMapper mapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-08 11:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/bookingTests/BookingControllerTest.java
> +    void createBooking() throws Exception {
Этот тест нужно разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Хороший юнит тест состоит из трех блоков кода:

1. Подготовка данных для теста
2. Вызов тестируемого метода
3. Проверка результатов

Важно, чтобы п.2 выполнялся однократно - так будет проще понять что пошло не так, если один или несколько тестов упадут.

Подробнее о хороших практиках юнит-тестирования можно прочитать тут:  https://www.baeldung.com/java-unit-testing-best-practices

Аналогично нужно поправить остальные подобные тесты.

2022-10-08 11:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/bookingTests/BookingRepositoryTests.java
> +    UserRepository userRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-08 11:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/bookingTests/BookingServiceTest.java
> +    BookingRepository bookingRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-08 11:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemTests/ItemControllerTest.java
> +    ObjectMapper mapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-08 11:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemTests/ItemMapperTest.java
> +    UserRepository userRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-08 11:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemTests/ItemRepositoryTests.java
> +    UserRepository userRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-08 11:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemTests/ItemServiceImplTest.java
> +    ItemRepository itemRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-08 11:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/userTests/UserControllerTest.java
> +    ObjectMapper mapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-08 11:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/userTests/UserServiceImplTest.java
> +    UserServiceImpl userService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-11 11:49 UTC, IgorMartynkin1981 commented on src/test/java/ru/practicum/shareit/bookingTests/BookingControllerTest.java
> +    ObjectMapper mapper;
Исправил

2022-10-11 11:51 UTC, IgorMartynkin1981 commented on src/test/java/ru/practicum/shareit/bookingTests/BookingControllerTest.java
> +    void createBooking() throws Exception {
Исправил. 
Почти закончил изучение "о хороших практиках юнит-тестирования", спасибо! Уже определил основные моменты в своих ошибках (одна из Плохое название методов - не отражают что хочу проверить)

2022-10-11 11:51 UTC, IgorMartynkin1981 commented on src/test/java/ru/practicum/shareit/bookingTests/BookingRepositoryTests.java
> +    UserRepository userRepository;
Исправил

2022-10-11 11:52 UTC, IgorMartynkin1981 commented on src/test/java/ru/practicum/shareit/bookingTests/BookingServiceTest.java
> +    BookingRepository bookingRepository;
Исправил

2022-10-11 11:52 UTC, IgorMartynkin1981 commented on src/test/java/ru/practicum/shareit/itemTests/ItemControllerTest.java
> +    ObjectMapper mapper;
Исправил

2022-10-11 11:52 UTC, IgorMartynkin1981 commented on src/test/java/ru/practicum/shareit/itemTests/ItemMapperTest.java
> +    UserRepository userRepository;
Исправил

2022-10-11 11:52 UTC, IgorMartynkin1981 commented on src/test/java/ru/practicum/shareit/itemTests/ItemRepositoryTests.java
> +    UserRepository userRepository;
Исправил

2022-10-11 11:52 UTC, IgorMartynkin1981 commented on src/test/java/ru/practicum/shareit/itemTests/ItemServiceImplTest.java
> +    ItemRepository itemRepository;
Исправил

2022-10-11 11:52 UTC, IgorMartynkin1981 commented on src/test/java/ru/practicum/shareit/userTests/UserControllerTest.java
> +    ObjectMapper mapper;
Исправил

2022-10-11 11:52 UTC, IgorMartynkin1981 commented on src/test/java/ru/practicum/shareit/userTests/UserServiceImplTest.java
> +    UserServiceImpl userService;
Исправил

2022-10-11 16:22 UTC, kukolev approved these changes

2022-10-15 10:05 UTC, merged