Refactor code ТЗ16
IgorMartynkin1981/java-shareit pull request #4
Opened 2022-10-23 15:52 UTC by IgorMartynkin1981

2022-10-24 11:49 UTC, kukolev requested changes
Не выполнено требование ТЗ: Нужно из shareId-server вынести в shareIt-gateway всю логику валидации входных данных — кроме той, которая требует работы с БД.

Сейчас в shareIt-server есть валидация входных параметров. Нужно этот код перенести в shareIt-gateway.

Таким образом:
1. Ни в одном из классов микросервиса shareIt-server не должно быть валидации входных параметров и DTO. Допускается только валидация при работе с БД.
2. Валидация входных параметров и DTO должна быть реализована только в микросервисе shareIt-gateway.
3. Файл pom.xml в shareIt-server не должен содержать никаких зависимостей на библиотеки валидации.

Валидация осталась тут:
- ru.practicum.shareit.booking.controllers.BookingController#createBooking
- ru.practicum.shareit.item.controllers.ItemController#createItem
- ru.practicum.shareit.item.services.ItemServiceImpl#verifyOnNullDataException
- ru.practicum.shareit.item.services.ItemServiceImpl#verifyCommentIsEmpty
- ru.practicum.shareit.user.controllers.UserController#createUser

2022-10-24 11:49 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-24 11:49 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookItemRequestDto.java
> +	private long itemId;
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-24 11:49 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-24 11:49 UTC, kukolev commented on server/pom.xml
> +	<modelVersion>4.0.0</modelVersion>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-24 11:49 UTC, kukolev commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-25 12:05 UTC, IgorMartynkin1981 commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +	public static void main(String[] args) {
Исправил

2022-10-25 12:06 UTC, IgorMartynkin1981 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookItemRequestDto.java
> +	private long itemId;
Исправил

2022-10-25 12:09 UTC, IgorMartynkin1981 commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
Исправил

2022-10-25 12:10 UTC, IgorMartynkin1981 commented on server/pom.xml
> +	<modelVersion>4.0.0</modelVersion>
Исправил

2022-10-25 12:10 UTC, IgorMartynkin1981 commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +	public static void main(String[] args) {
Исправил

2022-10-25 12:17 UTC, IgorMartynkin1981 commented
Замечания учтены, валидация входящих данных в servere удалена

2022-10-25 16:56 UTC, kukolev requested changes
Осталась одна валидация, пропущенная мной в прошлом ревью. Тем не менее нужно поправить: 

ru.practicum.shareit.booking.services.BookingServiceImpl#verifyCorrectBookingDates

В остальном работа хорошая, можно будет принять после исправления замечания.

2022-10-26 11:17 UTC, IgorMartynkin1981 commented
Замечания устранены

2022-10-26 15:12 UTC, kukolev approved these changes

2022-10-27 00:00 UTC, merged